version: '3.9'

services:

  # Review Service
  review-service:
    build: ./review-service
    ports:
      - "8181:8080"
    depends_on:
      - review-service-db
    networks:
      - review-network
      - course-review-network

  review-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5434:5432"
    networks:
      - review-network




  # Course Service
  course-service:
    build: ./course-service
    ports:
      - "8080:8080"
    depends_on:
      - course-service-db
    networks:
      - course-network
      - course-review-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course-service-db:5432/postgres
      REVIEW_SERVICE_URL:  http://review-service:8080/review_service_war_exploded/api/v1/reviews

  course-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"
    networks:
      - course-network



networks:
  review-network:
    driver: bridge
  course-network:
    driver: bridge
  course-review-network:
    driver: bridge



